version: '3.1'

services:
  db:
    container_name: NG-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password12
      - POSTGRES_USER=root
    ports:
      - 3002:5432

  backend:
    container_name: NG-backend
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=postgresql://root:password12@db:5432/mydb?schema=public
      - SECRET=senhasupersecreta
      - SALT=5
      - PORT=3001
